import type { Guide, GuideCategory, QuizQuestion, ScamAlert } from './supabase';

export const fallbackCategories: GuideCategory[] = [
  { id: 'c1', slug: 'scams-fraud', name: 'Scams & Fraud', pillar: 'safety', description: 'How to recognize and avoid online scams', created_at: '2026-08-01T00:00:00Z' },
  { id: 'c2', slug: 'account-security', name: 'Account Security', pillar: 'safety', description: 'Protecting your accounts and passwords', created_at: '2026-08-01T00:00:00Z' },
  { id: 'c3', slug: 'misinformation', name: 'Misinformation', pillar: 'safety', description: 'Spotting false information online', created_at: '2026-08-01T00:00:00Z' },
  { id: 'c4', slug: 'privacy', name: 'Privacy & Identity', pillar: 'safety', description: 'Keeping your personal information safe', created_at: '2026-08-01T00:00:00Z' },
  { id: 'c5', slug: 'remote-work', name: 'Remote Work', pillar: 'opportunities', description: 'Finding legitimate remote work', created_at: '2026-08-01T00:00:00Z' },
  { id: 'c6', slug: 'freelancing', name: 'Freelancing', pillar: 'opportunities', description: 'Building a freelancing career online', created_at: '2026-08-01T00:00:00Z' },
  { id: 'c7', slug: 'online-learning', name: 'Online Learning', pillar: 'opportunities', description: 'Learning new skills on the internet', created_at: '2026-08-01T00:00:00Z' },
  { id: 'c8', slug: 'digital-income', name: 'Digital Income', pillar: 'opportunities', description: 'Earning money through digital tools', created_at: '2026-08-01T00:00:00Z' },
];

export const fallbackGuides: Guide[] = [
  {
    id: 'g1',
    slug: 'mobile-money-fraud',
    title: 'Mobile Money Fraud: How to Protect Yourself',
    pillar: 'safety',
    category_slug: 'scams-fraud',
    tags: ['mobile money', 'fraud', 'scams', 'MPESA', 'Airtel Money'],
    difficulty: 'Beginner',
    read_time_minutes: 5,
    type: 'Article',
    language: 'en',
    summary: 'Learn how scammers trick mobile money users into sending money or sharing PINs, and the simple steps you can take to stay safe.',
    real_world_example: 'You receive a call from someone claiming to be from your mobile money provider. They say your account has a problem and they need your PIN to "fix" it. No real provider will ever ask for your PIN.',
    steps: [
      { title: 'Never share your PIN', body: 'Your mobile money PIN is yours alone. No legitimate agent, provider, or bank will ever ask for it. If someone asks for your PIN, it is a scam.' },
      { title: 'Verify before you send', body: 'Before sending money to anyone, call them on a known number to confirm it is really them. Scammers hack accounts and pretend to be your friends.' },
      { title: 'Check confirmation messages', body: 'Always wait for the SMS confirmation after a transaction. Do not trust the sender saying they received it — check your own phone.' },
      { title: 'Report suspicious activity', body: 'If you suspect fraud, call your mobile money provider immediately using the official number on the back of your SIM card or their website.' },
    ],
    mini_quiz: [
      {
        question: 'Someone calls saying they are from your mobile money provider and needs your PIN to fix a problem. What do you do?',
        options: ['Give them the PIN so they can fix it', 'Hang up and call the official number yourself', 'Give them a wrong PIN', 'Ask them to call back later'],
        answer_index: 1,
        explanation: 'No real provider will ever ask for your PIN. Hang up and call the official number to verify.',
      },
    ],
    sources_note: 'Based on consumer protection guidelines from the Reserve Bank of Malawi and mobile money provider security recommendations.',
    featured: true,
    featured_order: 1,
    published: true,
    last_updated: '2026-08-01',
    cover_emoji: '📱',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'g2',
    slug: 'phishing-messages',
    title: 'Spotting Phishing Messages',
    pillar: 'safety',
    category_slug: 'scams-fraud',
    tags: ['phishing', 'email', 'sms', 'scams'],
    difficulty: 'Beginner',
    read_time_minutes: 6,
    type: 'Article',
    language: 'en',
    summary: 'Phishing messages try to steal your passwords and personal information by pretending to be from trusted companies. Learn the warning signs.',
    real_world_example: 'You get an email that looks like it is from your bank, asking you to "verify your account" by clicking a link. The link goes to a fake website that steals your password.',
    steps: [
      { title: 'Check the sender address', body: 'Look carefully at the email address, not just the display name. Scammers use addresses that look almost right but have small differences.' },
      { title: 'Do not click suspicious links', body: 'Hover over a link before clicking to see where it really goes. When in doubt, do not click — go to the website directly instead.' },
      { title: 'Watch for urgency and threats', body: 'Phishing messages often create panic: "Your account will be closed!" or "Act now!" Real companies do not pressure you this way.' },
      { title: 'Look for spelling and grammar errors', body: 'Many phishing messages have obvious mistakes. Legitimate companies proofread their messages.' },
    ],
    mini_quiz: [
      {
        question: 'You receive an email saying your account will be closed in 24 hours unless you click a link to verify. What is the best action?',
        options: ['Click the link immediately', 'Delete the email and log in to your account directly', 'Forward it to all your contacts', 'Reply asking if it is real'],
        answer_index: 1,
        explanation: 'Urgency is a classic phishing trick. Never click the link — go to the website directly and log in to check.',
      },
    ],
    sources_note: 'Adapted from cybersecurity awareness resources from the Malawi Communications Regulatory Authority (MACRA).',
    featured: true,
    featured_order: 2,
    published: true,
    last_updated: '2026-08-02',
    cover_emoji: '🎣',
    created_at: '2026-08-02T00:00:00Z',
  },
  {
    id: 'g3',
    slug: 'fake-job-ads',
    title: 'How to Spot Fake Job Advertisements',
    pillar: 'safety',
    category_slug: 'scams-fraud',
    tags: ['jobs', 'scams', 'fraud', 'employment'],
    difficulty: 'Beginner',
    read_time_minutes: 7,
    type: 'Article',
    language: 'en',
    summary: 'Fake job ads promise easy money and high pay to trick you into paying fees or sharing personal information. Learn the red flags.',
    real_world_example: 'A WhatsApp message offers you a data entry job paying MK 150,000 per week, but first you must pay a MK 5,000 "registration fee." No real job asks you to pay to work.',
    steps: [
      { title: 'Never pay to get a job', body: 'If they ask for registration, training, or equipment fees, it is a scam. Real employers pay you, not the other way around.' },
      { title: 'Research the company', body: 'Search for the company name online. Check if they have a real website, real employees on LinkedIn, and a real physical address.' },
      { title: 'Be suspicious of high pay for easy work', body: 'If it sounds too good to be true, it is. Data entry, typing, and WhatsApp jobs do not pay huge salaries for no experience.' },
      { title: 'Check the contact method', body: 'Legitimate companies use official email addresses, not just WhatsApp numbers or personal phone numbers.' },
    ],
    mini_quiz: [
      {
        question: 'A job ad on WhatsApp offers MK 200,000/week for simple data entry but requires a MK 5,000 registration fee. What should you do?',
        options: ['Pay the fee to get started', 'Ignore it — it is a scam', 'Negotiate the fee down', 'Share it with friends'],
        answer_index: 1,
        explanation: 'No legitimate job requires you to pay money upfront. This is a classic fake job ad scam.',
      },
    ],
    sources_note: 'Based on employment scam warnings from the Malawi Labour Office and international consumer protection agencies.',
    featured: false,
    featured_order: 0,
    published: true,
    last_updated: '2026-08-03',
    cover_emoji: '💼',
    created_at: '2026-08-03T00:00:00Z',
  },
  {
    id: 'g4',
    slug: 'identity-theft',
    title: 'Protecting Your Identity Online',
    pillar: 'safety',
    category_slug: 'privacy',
    tags: ['identity theft', 'privacy', 'personal information'],
    difficulty: 'Intermediate',
    read_time_minutes: 8,
    type: 'Article',
    language: 'en',
    summary: 'Your identity is valuable. Learn how criminals steal personal information online and the steps you can take to keep yours safe.',
    real_world_example: 'Someone uses your name and ID number to open accounts in your name. You only find out when debt collectors start calling you.',
    steps: [
      { title: 'Limit what you share online', body: 'Do not post your full name, date of birth, ID number, or address on social media. Scammers use this information to impersonate you.' },
      { title: 'Use strong, unique passwords', body: 'Use a different password for each account. A password manager can help you keep track. Never use your name or birthdate as a password.' },
      { title: 'Enable two-factor authentication', body: 'Turn on 2FA for important accounts like email and banking. It adds a second step that makes it much harder for someone to break in.' },
      { title: 'Shred personal documents', body: 'Do not throw away papers with personal information. Tear them up or burn them so no one can read your details from the trash.' },
    ],
    mini_quiz: [
      {
        question: 'Which of these is the safest password?',
        options: ['yourname123', 'password', 'MyDog!B0nzo#2026', 'birthdate'],
        answer_index: 2,
        explanation: 'A strong password uses a mix of uppercase, lowercase, numbers, and symbols, and does not use personal information.',
      },
    ],
    sources_note: 'Based on identity protection guidelines from international cybersecurity organizations.',
    featured: false,
    featured_order: 0,
    published: true,
    last_updated: '2026-08-04',
    cover_emoji: '🔐',
    created_at: '2026-08-04T00:00:00Z',
  },
  {
    id: 'g5',
    slug: 'social-media-safety',
    title: 'Staying Safe on Social Media',
    pillar: 'safety',
    category_slug: 'privacy',
    tags: ['social media', 'privacy', 'facebook', 'whatsapp'],
    difficulty: 'Beginner',
    read_time_minutes: 5,
    type: 'Article',
    language: 'en',
    summary: 'Social media connects us with friends and family, but it also has risks. Learn how to use Facebook, WhatsApp, and other platforms safely.',
    real_world_example: 'A stranger sends you a friend request on Facebook. Their profile has only one photo and was created last week. It could be a fake account trying to scam you.',
    steps: [
      { title: 'Check your privacy settings', body: 'On Facebook, set your posts to "Friends only" instead of "Public." This stops strangers from seeing your personal information.' },
      { title: 'Be careful with friend requests', body: 'Do not accept requests from people you do not know. Fake accounts are used to build trust before asking for money or information.' },
      { title: 'Think before you post', body: 'Do not share your location, travel plans, or photos of valuable items. Criminals can use this information.' },
      { title: 'Report and block suspicious users', body: 'If someone makes you uncomfortable or sends strange messages, block them and report the account to the platform.' },
    ],
    mini_quiz: [],
    sources_note: 'Adapted from social media safety guides from Facebook and WhatsApp security centers.',
    featured: false,
    featured_order: 0,
    published: true,
    last_updated: '2026-08-05',
    cover_emoji: '👥',
    created_at: '2026-08-05T00:00:00Z',
  },
  {
    id: 'g6',
    slug: 'misinformation',
    title: 'How to Spot False News and Misinformation',
    pillar: 'safety',
    category_slug: 'misinformation',
    tags: ['misinformation', 'fake news', 'media literacy'],
    difficulty: 'Intermediate',
    read_time_minutes: 7,
    type: 'Article',
    language: 'en',
    summary: 'Not everything you read online is true. Learn how to check if a story is real before you believe it or share it with others.',
    real_world_example: 'A WhatsApp message claims that drinking salt water cures a disease. It says "forward this to everyone you know!" There is no medical proof, but people believe it because it came from a friend.',
    steps: [
      { title: 'Check the source', body: 'Is the news from a trusted news organization or an unknown blog? If you cannot find the original source, be suspicious.' },
      { title: 'Look for other reports', body: 'If only one source is reporting something, wait. Real news is usually reported by multiple outlets.' },
      { title: 'Check the date', body: 'Old stories are often shared as if they are new. Check when the article was first published.' },
      { title: 'Do not forward without checking', body: 'Before you share, ask yourself: am I sure this is true? Sharing false information can cause real harm.' },
    ],
    mini_quiz: [
      {
        question: 'A WhatsApp message tells you to forward urgent health advice to everyone. What should you do?',
        options: ['Forward it immediately to help people', 'Check if a trusted health organization confirms it first', 'Ignore it completely', 'Reply to the sender with thanks'],
        answer_index: 1,
        explanation: 'Always verify health information with trusted sources like the WHO or Ministry of Health before sharing.',
      },
    ],
    sources_note: 'Based on media literacy resources from UNESCO and the Media Institute of Southern Africa (MISA).',
    featured: false,
    featured_order: 0,
    published: true,
    last_updated: '2026-08-06',
    cover_emoji: '📰',
    created_at: '2026-08-06T00:00:00Z',
  },
  {
    id: 'g7',
    slug: 'remote-work-guide',
    title: 'Finding Real Remote Work Online',
    pillar: 'opportunities',
    category_slug: 'remote-work',
    tags: ['remote work', 'jobs', 'online income'],
    difficulty: 'Beginner',
    read_time_minutes: 8,
    type: 'Article',
    language: 'en',
    summary: 'Remote work lets you earn money from anywhere. Learn how to find legitimate remote jobs and avoid scams along the way.',
    real_world_example: 'A young woman in Lilongwe found a customer service job on a legitimate platform. She works from home on her phone and earns in foreign currency, which is worth more in Kwacha.',
    steps: [
      { title: 'Use trusted job platforms', body: 'Start with platforms like Upwork, Fiverr, and Remote.com. These platforms verify employers and hold your payment safely.' },
      { title: 'Build a profile that stands out', body: 'Create a clear profile with your skills, a professional photo, and examples of your work. Complete any platform tests to show your abilities.' },
      { title: 'Start with small jobs', body: 'Do not expect high pay immediately. Start with small projects, build good reviews, and your reputation will grow.' },
      { title: 'Never pay for a job', body: 'If a job requires you to pay a fee, buy equipment from them, or send money, it is a scam. Real jobs pay you.' },
    ],
    mini_quiz: [],
    sources_note: 'Based on remote work guides from Upwork, Fiverr, and remote work communities.',
    featured: true,
    featured_order: 3,
    published: true,
    last_updated: '2026-08-03',
    cover_emoji: '💻',
    created_at: '2026-08-03T00:00:00Z',
  },
  {
    id: 'g8',
    slug: 'freelancing-guide',
    title: 'Getting Started with Freelancing',
    pillar: 'opportunities',
    category_slug: 'freelancing',
    tags: ['freelancing', 'income', 'skills', 'upwork', 'fiverr'],
    difficulty: 'Intermediate',
    read_time_minutes: 10,
    type: 'Article',
    language: 'en',
    summary: 'Freelancing means offering your skills to clients online. This guide walks you through choosing a skill, finding clients, and getting paid.',
    real_world_example: 'A graphic designer in Blantyre creates logos for clients around the world on Fiverr. He started with MK 5,000 jobs and now charges MK 50,000+ per logo.',
    steps: [
      { title: 'Choose your skill', body: 'What can you do that others will pay for? Writing, design, translation, data entry, virtual assistance, and programming are all in demand.' },
      { title: 'Create profiles on freelancing platforms', body: 'Sign up on Upwork, Fiverr, or Freelancer.com. Fill out your profile completely — it is your online resume.' },
      { title: 'Price your services competitively', body: 'Start with lower prices to get your first clients and reviews. Raise your prices as you build a good reputation.' },
      { title: 'Deliver quality and communicate well', body: 'Happy clients leave good reviews, which bring more clients. Always communicate clearly and deliver on time.' },
      { title: 'Get paid safely', body: 'Use platform payment systems, not direct transfers. Platforms hold your money in escrow until the work is approved.' },
    ],
    mini_quiz: [
      {
        question: 'A client on a freelancing platform asks you to communicate on WhatsApp and accept payment via direct bank transfer instead of through the platform. What should you do?',
        options: ['Agree — it seems easier', 'Refuse and keep all communication and payment on the platform', 'Give them your bank details', 'Ask for half payment upfront directly'],
        answer_index: 1,
        explanation: 'Keeping everything on the platform protects you. Off-platform deals have no protection if the client does not pay.',
      },
    ],
    sources_note: 'Based on freelancing guides from Upwork, Fiverr, and successful freelancers in Africa.',
    featured: false,
    featured_order: 0,
    published: true,
    last_updated: '2026-08-04',
    cover_emoji: '🚀',
    created_at: '2026-08-04T00:00:00Z',
  },
  {
    id: 'g9',
    slug: 'online-learning',
    title: 'Learning New Skills Online for Free',
    pillar: 'opportunities',
    category_slug: 'online-learning',
    tags: ['learning', 'education', 'skills', 'free courses'],
    difficulty: 'Beginner',
    read_time_minutes: 6,
    type: 'Article',
    language: 'en',
    summary: 'The internet has thousands of free courses to help you learn new skills. This guide shows you where to find them and how to succeed.',
    real_world_example: 'A student in Mzuzu learned computer programming for free on freeCodeCamp and now works as a junior developer, earning in US dollars.',
    steps: [
      { title: 'Find free learning platforms', body: 'Websites like Coursera, edX, Khan Academy, and freeCodeCamp offer free courses from top universities and organizations.' },
      { title: 'Choose a skill that is in demand', body: 'Digital marketing, programming, graphic design, data analysis, and writing are all skills you can learn online and use to earn money.' },
      { title: 'Set a regular study schedule', body: 'Treat online learning like a real class. Set aside specific times each week and stick to them.' },
      { title: 'Practice with real projects', body: 'Do not just watch videos — build things. Practice projects help you learn faster and give you a portfolio to show employers.' },
    ],
    mini_quiz: [],
    sources_note: 'Based on online learning resources from Coursera, edX, Khan Academy, and freeCodeCamp.',
    featured: false,
    featured_order: 0,
    published: true,
    last_updated: '2026-08-05',
    cover_emoji: '📚',
    created_at: '2026-08-05T00:00:00Z',
  },
  {
    id: 'g10',
    slug: 'digital-entrepreneurship',
    title: 'Starting a Digital Business with Low Capital',
    pillar: 'opportunities',
    category_slug: 'digital-income',
    tags: ['entrepreneurship', 'business', 'income', 'digital'],
    difficulty: 'Advanced',
    read_time_minutes: 12,
    type: 'Article',
    language: 'en',
    summary: 'You do not need a lot of money to start a digital business. Learn how to use your phone and the internet to create income opportunities.',
    real_world_example: 'A woman in Zomba started selling homemade crafts on Facebook Marketplace with just her phone. She now sells to customers across Malawi and has hired two helpers.',
    steps: [
      { title: 'Identify a problem you can solve', body: 'Every business solves a problem. What do people in your community need that you can provide using digital tools?' },
      { title: 'Start with what you have', body: 'Your phone is your office. Use free tools: WhatsApp Business, Facebook Marketplace, and Google Forms for orders.' },
      { title: 'Build trust with customers', body: 'Post clear photos, respond quickly, and deliver what you promise. Happy customers recommend you to others.' },
      { title: 'Reinvest your profits', body: 'Do not spend all your earnings. Put some back into the business to grow — buy better tools, run ads, or expand your products.' },
      { title: 'Learn basic digital marketing', body: 'Learn how to use social media to reach more customers. Free courses on digital marketing are available online.' },
    ],
    mini_quiz: [],
    sources_note: 'Based on entrepreneurship guides from the Malawi Investment and Trade Centre and digital business resources.',
    featured: false,
    featured_order: 0,
    published: true,
    last_updated: '2026-08-06',
    cover_emoji: '🏪',
    created_at: '2026-08-06T00:00:00Z',
  },
  {
    id: 'g11',
    slug: 'spotting-legitimate-opportunity',
    title: 'How to Tell if an Online Opportunity is Real',
    pillar: 'opportunities',
    category_slug: 'remote-work',
    tags: ['scams', 'jobs', 'verification', 'opportunities'],
    difficulty: 'Beginner',
    read_time_minutes: 5,
    type: 'Article',
    language: 'en',
    summary: 'Before you invest time or money in an online opportunity, use this checklist to make sure it is legitimate.',
    real_world_example: 'You see an ad for an online survey job that pays MK 50,000/month for 1 hour of work per day. Before signing up, you check and find no real company name, no website, and only a WhatsApp number.',
    steps: [
      { title: 'Check for a real company name', body: 'A legitimate opportunity comes from a real, named company. Search for the company online — can you find their website and reviews?' },
      { title: 'Verify on official platforms', body: 'If the job is on Upwork, Fiverr, or a known job board, it is more likely to be real. Opportunities that exist only on WhatsApp are risky.' },
      { title: 'Look for clear job details', body: 'A real opportunity has a clear description: what you do, how much you earn, and when you get paid. Vague promises are a red flag.' },
      { title: 'Trust your instincts', body: 'If something feels wrong, it probably is. Talk to someone you trust before committing to any online opportunity.' },
    ],
    mini_quiz: [
      {
        question: 'An online opportunity has no company name, no website, and only a WhatsApp number. What should you do?',
        options: ['Sign up and hope for the best', 'Be very cautious — these are scam warning signs', 'Send them money to learn more', 'Give them your ID copy'],
        answer_index: 1,
        explanation: 'No company name, no website, and only WhatsApp contact are major red flags. Be very cautious.',
      },
    ],
    sources_note: 'Based on consumer protection resources and online job verification guides.',
    featured: false,
    featured_order: 0,
    published: true,
    last_updated: '2026-08-07',
    cover_emoji: '🔍',
    created_at: '2026-08-07T00:00:00Z',
  },
];

export const fallbackQuizQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    scenario_type: 'sms',
    prompt: 'You receive this SMS. Is it real or a scam?',
    message_body: 'CONGRATULATIONS! You have won MK 500,000 in the Airtel Lucky Draw! To claim your prize, send MK 2,000 to this number: 0999 12 34 56',
    is_real: false,
    explanation: 'You did not enter any lottery. Real lotteries do not ask you to pay money to claim a prize. This is a classic advance-fee scam.',
    warning_signs: ['You did not enter any contest', 'Asked to pay money to receive money', 'Urgency and excitement to cloud judgment', 'Only a phone number, no official channel'],
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'q2',
    scenario_type: 'email',
    prompt: 'You receive this email. Is it real or a scam?',
    message_body: 'Dear Customer,\n\nWe have detected unusual activity on your bank account. Your account has been temporarily suspended for security reasons.\n\nTo restore access, please click here and verify your credentials:\n\nhttp://secure-bank-verify.ml/login\n\nIf you do not verify within 24 hours, your account will be permanently closed.',
    is_real: false,
    explanation: 'This is a phishing email. The link goes to a fake website. Real banks never ask you to verify credentials via email links. The urgency ("24 hours") is designed to make you panic.',
    warning_signs: ['Suspicious URL (not the real bank website)', 'Creates false urgency', 'Asks for credentials via email link', 'Generic greeting ("Dear Customer")'],
    created_at: '2026-08-02T00:00:00Z',
  },
  {
    id: 'q3',
    scenario_type: 'whatsapp',
    prompt: 'You receive this WhatsApp message from a friend. Is it real or a scam?',
    message_body: 'Hi! I got a new number. I am in a meeting and cannot talk, but I need urgent help. I need to pay someone MK 15,000 right now. Can you send it to this number? I will pay you back tomorrow.',
    is_real: false,
    explanation: 'This is the "friend in need" scam. Scammers hack or impersonate WhatsApp accounts and send messages to contacts asking for money. Always call your friend on their old number to verify.',
    warning_signs: ['New number — claims to be a friend', 'Cannot talk (only text)', 'Creates urgency', 'Asks for money to be sent to a different number'],
    created_at: '2026-08-03T00:00:00Z',
  },
  {
    id: 'q4',
    scenario_type: 'job_ad',
    prompt: 'You see this job advertisement. Is it real or a scam?',
    message_body: 'URGENT HIRING: Data Entry Work from Home\n\nEarn MK 150,000 - MK 300,000 per week!\nNo experience needed!\nFlexible hours — work from your phone!\n\nTo apply, send MK 3,000 registration fee to 0999 88 77 66 via Airtel Money.',
    is_real: false,
    explanation: 'This is a fake job ad. No legitimate job requires you to pay a registration fee. The extremely high pay for "no experience" data entry is unrealistic. The only contact is a mobile money number.',
    warning_signs: ['Requires payment to apply', 'Extremely high pay for simple work', 'No experience needed for high salary', 'Only contact is a mobile money number'],
    created_at: '2026-08-04T00:00:00Z',
  },
  {
    id: 'q5',
    scenario_type: 'sms',
    prompt: 'You receive this SMS from your mobile money provider. Is it real or a scam?',
    message_body: 'You have received MK 5,000 from CHIYEMBEKEZO BANDA. New balance: MK 12,500. Transaction ID: MP230807.1234. Reference: Payment for vegetables.',
    is_real: true,
    explanation: 'This is a legitimate mobile money confirmation message. It includes the sender name, amount, new balance, and a transaction ID. It does not ask you to do anything or share any information.',
    warning_signs: [],
    created_at: '2026-08-05T00:00:00Z',
  },
  {
    id: 'q6',
    scenario_type: 'email',
    prompt: 'You receive this email after applying for a job on a legitimate platform. Is it real or a scam?',
    message_body: 'Dear Applicant,\n\nThank you for applying for the Customer Service Representative position at TechSupport Ltd. We have reviewed your application and would like to invite you for an online interview.\n\nThe interview will take place on Tuesday at 10:00 AM via Google Meet. Please confirm your availability by replying to this email.\n\nBest regards,\nHR Department\nTechSupport Ltd',
    is_real: true,
    explanation: 'This is a legitimate job interview invitation. It comes from a company you applied to, includes specific details (date, time, platform), and does not ask for money or sensitive information. It asks you to reply through the same email channel.',
    warning_signs: [],
    created_at: '2026-08-06T00:00:00Z',
  },
];

export const fallbackScamAlerts: ScamAlert[] = [
  {
    id: 'a1',
    title: 'Fake Airtel Lottery SMS asking for MK 2,000 to claim MK 500,000 prize',
    summary: 'SMS scam targeting Airtel users with fake lottery winnings',
    severity: 'high',
    active: true,
    created_at: '2026-08-07T00:00:00Z',
  },
  {
    id: 'a2',
    title: 'WhatsApp "friend in need" scam — hacked accounts asking for mobile money',
    summary: 'Scammers hijack WhatsApp accounts and message contacts asking for urgent money transfers',
    severity: 'high',
    active: true,
    created_at: '2026-08-06T00:00:00Z',
  },
  {
    id: 'a3',
    title: 'Fake data entry job ads on Facebook requiring MK 3,000 registration fee',
    summary: 'Facebook job scam promising high pay for data entry but requiring upfront payment',
    severity: 'medium',
    active: true,
    created_at: '2026-08-05T00:00:00Z',
  },
];
